// <auto-generated />
using System;
using Catalogo.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalogo.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Catalogo.Dominio.BibliotecaJogos.BibliotecaJogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BibliotecaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BibliotecaId");

                    b.HasIndex("JogoId");

                    b.ToTable("bibliotecaJogo", (string)null);
                });

            modelBuilder.Entity("Catalogo.Dominio.Bibliotecas.Biblioteca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("biblioteca", (string)null);
                });

            modelBuilder.Entity("Catalogo.Dominio.Jogos.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("jogo", (string)null);
                });

            modelBuilder.Entity("Catalogo.Dominio.BibliotecaJogos.BibliotecaJogo", b =>
                {
                    b.HasOne("Catalogo.Dominio.Bibliotecas.Biblioteca", "Biblioteca")
                        .WithMany("BibliotecaJogos")
                        .HasForeignKey("BibliotecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalogo.Dominio.Jogos.Jogo", "Jogo")
                        .WithMany("BibliotecaJogos")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biblioteca");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("Catalogo.Dominio.Bibliotecas.Biblioteca", b =>
                {
                    b.Navigation("BibliotecaJogos");
                });

            modelBuilder.Entity("Catalogo.Dominio.Jogos.Jogo", b =>
                {
                    b.Navigation("BibliotecaJogos");
                });
#pragma warning restore 612, 618
        }
    }
}
