apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog-api
  labels:
    app: catalog-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: catalog-api

  template:
    metadata:
      labels:
        app: catalog-api

    spec:
      containers:
        - name: catalog-api
          image: seuusuario/catalog-api:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development

            - name: RabbitMQ__Host
              value: rabbitmq