apiVersion: v1
kind: Secret

metadata:
  name: catalog-secret

type: Opaque

stringData:
  RabbitMQConnection: "amqp://guest:guest@rabbitmq:5672/"
  ConnectionStrings__Default: Data Source=catalodb.db